version: '3.8'

services:
  db:
    image: postgres:17
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RMS
    ports:
      - "5432:5432"
    volumes:
      - rms_data:/var/lib/postgresql/data

volumes:
  rms_data:
